site_name: Daiquiri documentation

nav:
  - Home: index.md
  - Installation: installation.md
  - Deployment: deployment.md
  - Settings: settings.md
  - Appendix: appendix.md

theme:
    name: readthedocs

markdown_extensions:
- def_list
- footnotes
- tables
- smarty

extra_css:
  - style.css
